version: '3'

services:
  airflow:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
     - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_LOGIN: ${DB_LOGIN}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_CONN_ID: ${DB_CONN_ID}
    container_name: ${CONTAINER_NAME}
  mysql:
    image: "mysql:5.7"
    ports:
     - "3307:3306"
    volumes:
     - ../sql/test_db_mysql:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
    container_name: mysql

networks:
  default:
    driver: bridge